sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty          
          env: VERSION=6
        - os: linux
          dist: trusty          
          env: VERSION=5
        # Use generic language for osx
        - os: osx
          osx_image: xcode8
          language: generic

install:
    - bash script/install-unix.sh
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
script:
    - bash script/travis-build.sh
notifications:
    slack:
        secure: "SeqNZUck0sPFvo+xgHVGNKn/zALCFYS/KQjiOiVjmOLlfVJTWT8YxDLqqm9RleTA4+VWL2h1nPWJuhAnRof8zHCuo5Ox+MO/VaHvcFvW4qu9hfMu0LmYTanJK2umf9E7dEnyi0Cip4DX/9LEzPyJqaO4pNQRelOFRI8UTHGqXLYbZmZVSxWgRw9Dvln2l/fMjop7zO6Ao/UtUCcJIOYAqpJuXV77HfPob8v5zT/tpJ4R8qhpVQBGDNw8PuwS4OHsm7jTSBVAr21t+XaW5LxFKh80t2KcO/ZlIcpEmm/O9TdYLor68B8ZroUsCtbX88pZCM+aJVlaFrxecODvFXpVY6eC/V7epdKUMdxO3T2aDNXd8wkOqJpht2Ndrb4J9b+FeLXYaKktDFOxdvYER/PSTM2mLZMc/JPKKmINlHBHL3+UQMTv1H9xZZJk6pYqybwxz3OYiYjiPMYF04igPZvzOKFa1QCGP3IzGJ/ZDDOZlVCuF1TyFYpyTE+9+4Fvtfwsh/ORzo9cWsxvWuJEK+wCQ/Lzx1mN0/CTa3KNeLgLUo2x8lot3UWEoFbXmvBH9RbSzqjIyLZ5ddjOxK+gc0+I6F1aRKrICWbmgUGEy3NLq6ZHCYCrLSn7ZPANxI6jVjtGb3BCqwRFHIIb9N5cj0au5HaW3lC+OsKpjel/e5r5sGA="